-- MySQL Script generated by MySQL Workbench
-- 03/04/17 23:18:45
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema test
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema test
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `test` ;
USE `test` ;

-- -----------------------------------------------------
-- Table `test`.`USER`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `test`.`USER` (
  `ID` INT(8) NOT NULL AUTO_INCREMENT,
  `NAME` VARCHAR(25) NOT NULL,
  `AGE` INT NOT NULL,
  `ISADMIN` TINYINT(1) NOT NULL DEFAULT '0',
  `CREATEDDATE` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`ID`))
  ENGINE = InnoDB
  DEFAULT CHARACTER SET = utf8;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

-- -----------------------------------------------------
-- Data for table `test`.`USER`
-- -----------------------------------------------------
START TRANSACTION;
USE `test`;
INSERT INTO `test`.`USER` (`ID`, `NAME`, `AGE`, `ISADMIN`, `CREATEDDATE`) VALUES (1, 'Amigo', 20,  0, '2017-02-28 11:49:23');
INSERT INTO `test`.`USER` (`ID`, `NAME`, `AGE`, `ISADMIN`, `CREATEDDATE`) VALUES (2, 'Klark', 50,  0, '2017-02-28 11:51:32');
INSERT INTO `test`.`USER` (`ID`, `NAME`, `AGE`, `ISADMIN`, `CREATEDDATE`) VALUES (3, 'Aika', 33,  0, '2017-02-28 11:52:12');
INSERT INTO `test`.`USER` (`ID`, `NAME`, `AGE`, `ISADMIN`, `CREATEDDATE`) VALUES (4, 'user', 30,  0, '2017-02-28 11:53:09');
INSERT INTO `test`.`USER` (`ID`, `NAME`, `AGE`, `ISADMIN`, `CREATEDDATE`) VALUES (5, 'admin', 16, 1, '2017-02-28 11:53:40');
INSERT INTO `test`.`USER` (`ID`, `NAME`, `AGE`, `ISADMIN`, `CREATEDDATE`) VALUES (6, 'Kurse', 12, 0, '2017-02-28 11:54:29');
INSERT INTO `test`.`USER` (`ID`, `NAME`, `AGE`, `ISADMIN`, `CREATEDDATE`) VALUES (7, 'Pagin', 100, 0, '2017-02-28 11:56:15');
INSERT INTO `test`.`USER` (`ID`, `NAME`, `AGE`, `ISADMIN`, `CREATEDDATE`) VALUES (8, 'user', 40, 0, '2017-02-28 11:57:27');
INSERT INTO `test`.`USER` (`ID`, `NAME`, `AGE`, `ISADMIN`, `CREATEDDATE`) VALUES (9, 'Klark', 36, 0, '2017-02-28 11:58:09');
INSERT INTO `test`.`USER` (`ID`, `NAME`, `AGE`, `ISADMIN`, `CREATEDDATE`) VALUES (10, 'Magic', 200, 0, '2017-02-28 11:58:39');
INSERT INTO `test`.`USER` (`ID`, `NAME`, `AGE`, `ISADMIN`, `CREATEDDATE`) VALUES (11, 'Warikar', 15, 0, '2017-02-28 11:59:35');
INSERT INTO `test`.`USER` (`ID`, `NAME`, `AGE`, `ISADMIN`, `CREATEDDATE`) VALUES (12, 'Karito', 55,  0, '2017-02-28 12:00:23');

COMMIT;